apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: argo-workflows
  annotations:
    workflows.argoproj.io/default-artifact-repository: default-s3
data:
  default-s3: |
    s3:
      endpoint: ams3.digitaloceanspaces.com
      bucket: fx-swarm-artifacts
      region: ams3
      insecure: false
      accessKeySecret:
        name: argo-data-science-swarm
        key: AWS_ACCESS_KEY_ID
      secretKeySecret:
        name: argo-data-science-swarm
        key: AWS_SECRET_ACCESS_KEY
